#! /usr/bin/env bash

out_dir='out/'
jar_file='jar/WordCount.jar'
class_name='ru.mipt.examples.WordCount'
input='/data/wiki/en_articles_part'

# Build project
ant clean && ant
# Remove previous results
hadoop fs -rm -r -skipTrash $out_dir*
# Run task
hadoop jar $jar_file $class_name $input $out_dir

