#! /bin/bash

mapper="python mapper.py"
reducer="python reducer.py"
input='/data/griboedov'
output='streaming/out'

# Remove previous results
hadoop fs -rm -r -skipTrash "streaming/out"
# Run
hadoop jar /opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hadoop-mapreduce/hadoop-streaming.jar \
   -file "./mapper.py" \
   -mapper "./mapper.py" \
   -file "./reducer.py" \
   -reducer "./reducer.py" \
   -input $input \
   -output $output
