#! /bin/bash

mapper="python mapper.py"
reducer="python reducer.py"
input='streaming/out'
output='streaming/out2'

# Remove previous results
hadoop fs -rm -r -skipTrash "streaming/out2"
# Run
hadoop jar /opt/cloudera/parcels/CDH-5.9.0-1.cdh5.9.0.p0.23/lib/hadoop-mapreduce/hadoop-streaming.jar \
   -D mapred.reduce.tasks=1 \
   -file "./mapper2.py" \
   -mapper "./mapper2.py" \
   -file "./reducer2.py" \
   -reducer "./reducer2.py" \
   -input $input \
   -output $output
